# See http://www.appveyor.com/docs/appveyor-yml for many more options

# set the clone folder for the project
clone_folder: C:\projects\PSGSuite

#Publish to PowerShell Gallery with this key
environment:
  NuGetApiKey:
    secure: Ocp1ATd6eZ0eY9+LfZ9Stp9/J1B5eFdBPMdaTRWVa4xh6/NV45ZBYtU5+eemrTWt
  fast_finish: true
  matrix:
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        PowershellVersion: "6.0.0"
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

#Kick off the CI/CD pipeline
test_script:
  - cmd: if %PowershellVersion:~0,1% gtr 5 (pwsh -Command ". .\ci\init.ps1") else (powershell -Command ". .\ci\init.ps1")